[project]
name = "pixi-0.8"
version = "0.1.0"
authors = ["Hofer-Julian <julianhofer@gnome.org>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]

[tasks]
install = "pip install --editable python"
import = { cmd = "python -c 'import test_package'" }

[dependencies]
python = "3.12.0.*"
pip = "23.3.1.*"
